id: I7BE641A4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T16:21:11+00:00'
last_modified: '2022-06-09T07:30:07.316880+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22156
  title: གླིང་དཔའ་བརྟུལ་བརྒྱད་བཅུའི་རྣམ་ཐར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '4344':
      image_group_id: I4820
      title: ''
      total_pages: 640
      order: 1
      base_file: 4344.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
