id: P007919
initial_creation_type: ocr
source_metadata:
  id: bdr:W22156
  title: གླིང་དཔའ་བརྟུལ་བརྒྱད་བཅུའི་རྣམ་ཐར
  author: ''
  volumes:
    80e986ae15104a4fb763df4f636ddc60:
      image_group_id: I4820
      title: ''
      volume_number: 1
      total_pages: 640
ebook_metadata:
  title: གླིང་དཔའ་བརྟུལ་བརྒྱད་བཅུའི་རྣམ་ཐར
  author: ''
  sku: P007919
  cover: cover.jpg
  layers:
  - pagination
