id: P007919
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 12:49:11.554941
source_metadata:
  id: bdr:W22156
  title: གླིང་དཔའ་བརྟུལ་བརྒྱད་བཅུའི་རྣམ་ཐར
  author: ''
  volumes:
    80e986ae15104a4fb763df4f636ddc60:
      image_group_id: I4820
      title: ''
      volume_number: 1
      total_pages: 640
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
