id: opecha:P007919
initial_creation_type: ocr
source_metadata:
  id: bdr:W22156
  title: གླིང་དཔའ་བརྟུལ་བརྒྱད་བཅུའི་རྣམ་ཐར
  volume:
    9a9a898acddf40c7af80bbf54794657d:
      image_group_id: I4820
      title: ''
      volume_number: 1
      total_pages: 640
  author: ''
ebook_metadata:
  title: གླིང་དཔའ་བརྟུལ་བརྒྱད་བཅུའི་རྣམ་ཐར
  author: ''
  sku: P007919
  cover: cover.jpg
  layers:
  - pagination
